config/routes.rb
Rails.application.routes.draw do
  root 'trades#index'
  resources :trades
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'market' => 'trades#markets'
end

app/models/trade.rb
class Trade < ApplicationRecord
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  before_action :set_trade, only: [:show, :edit, :update, :destroy]

  # GET /trades
  # GET /trades.json
  def index
    @trades = Trade.all
  end

  # GET /trades/1
  # GET /trades/1.json
  def show
  end

  # GET /trades/new
  def new
    @trade = Trade.new
  end

  # GET /trades/1/edit
  def edit
  end

  # POST /trades
  # POST /trades.json
  def create
    @trade = Trade.new(trade_params)

    respond_to do |format|
      if @trade.save
        format.html { redirect_to @trade, notice: 'Trade was successfully created.' }
        format.json { render :show, status: :created, location: @trade }
      else
        format.html { render :new }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trades/1
  # PATCH/PUT /trades/1.json
  def update
    respond_to do |format|
      if @trade.update(trade_params)
        format.html { redirect_to @trade, notice: 'Trade was successfully updated.' }
        format.json { render :show, status: :ok, location: @trade }
      else
        format.html { render :edit }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trades/1
  # DELETE /trades/1.json
  def destroy
    @trade.destroy
    respond_to do |format|
      format.html { redirect_to trades_url, notice: 'Trade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def markets
    p 'markets inside'
    respond_to do |format|
      p 'js inside'
      format.js
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trade
      @trade = Trade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trade_params
      params.fetch(:trade, {})
    end
end

app/helpers/trades_helper.rb
module TradesHelper
  def all_markets
    getmarkets
  end
end

app/views/trades/_form.html.erb
<%= form_with(model: trade, local: true) do |form| %>
  <% if trade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trade.errors.count, "error") %> prohibited this trade from being saved:</h2>

      <ul>
      <% trade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trades/_markets.html.erb
<% response.each do |r| %>
  <% r.each do |k, v| %>
    <%= k  %> : <%= v  %> <br>
  <% end %>
<% end %>

app/views/trades/edit.html.erb
<h1>Editing Trade</h1>

<%= render 'form', trade: @trade %>

<%= link_to 'Show', @trade %> |
<%= link_to 'Back', trades_path %>

app/views/trades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trades</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trades.each do |trade| %>
      <tr>
        <td><%= link_to 'Show', trade %></td>
        <td><%= link_to 'Edit', edit_trade_path(trade) %></td>
        <td><%= link_to 'Destroy', trade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trade', new_trade_path %>
<%= link_to 'Get Markets', market_path, method: :get, remote: true%>
<div class='market-list'>
</div>

app/views/trades/markets.js.erb
$('.market-list').html("<%= j render partial: 'markets', locals:{response: all_markets} %>")

app/views/trades/new.html.erb
<h1>New Trade</h1>

<%= render 'form', trade: @trade %>

<%= link_to 'Back', trades_path %>

app/views/trades/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_trade_path(@trade) %> |
<%= link_to 'Back', trades_path %>